// Copyright (C) 2025-2026  Roman Lyubimov
// SPDX-License-Identifier: GPL-3.0-or-later
// For full license text, see <https://www.gnu.org/licenses/gpl-3.0.txt>

#include "transfersessionlist.h"
#include "client.h"
#include "observerpattern.h"
#include "transfersession.h"
#include "config/config.h"

#include "log.h"

#include <mutex>

TransferSessionList::~TransferSessionList()
{
    m_ioContext.stop();
    if (m_ioContextThreadPtr && m_ioContextThreadPtr->joinable())
    {
        m_ioContextThreadPtr->join();
    }
}

TransferSessionList &TransferSessionList::instanse()
{
    static TransferSessionList list;
    return list;
}

TransferSessionList::SessionAndTimeout TransferSessionList::create(std::shared_ptr<Client> creator,
                                                                   const TransferSession::Options& options)
{
    if (creator == nullptr) return {nullptr, 0};

    std::unique_lock lock (m_mutex);

    /*
     * The session identifier is equal to the public identifier of its creator,
     * in order to avoid difficulties in detecting attempts to create multiple
     * sessions by one client.
     */
    const std::string id = creator->publicId();
    while (m_map.contains(id))
    {
        return {nullptr, 0};
    }

    auto session = createSubscriber<TransferSession>(creator, id, m_ioContext, options);
    session->initTimers(session);

    session->Publisher<Event::TransferSession>::addSubscriber(creator);
    session->Publisher<Event::TransferSessionForSender>::addSubscriber(creator);
    creator->Publisher<Event::ClientInternal>::addSubscriber(session);

    auto [iter, _] = m_map.try_emplace(
        id,
        SessionWithTimer {
            session,
            {
                m_ioContext,
                [this, session, id](){
                    session->setTimedout();
                    this->remove(id);
                },
                TimerCallback::Duration(Config::instance().transferSessionMaxLifetime())
            }
        }
    );

    if (iter == m_map.end())
    {
        PLOG_ERROR << "TransferSessionList::create - invalid iterator";
        return {nullptr, 0};
    }

    auto &timer = iter->second.timer;
    timer.start();

    return {session, timer.timeRemaining().count()};
}

TransferSessionList::SessionAndTimeout TransferSessionList::get(const std::string &id)
{
    std::shared_lock lock (m_mutex);

    const auto iter = m_map.find(id);
    if (iter == m_map.end())
    {
        return {nullptr, 0};
    }

    return {iter->second.session, iter->second.timer.timeRemaining().count()};
}

size_t TransferSessionList::count() const
{
    std::shared_lock lock (m_mutex);
    return m_map.size();
}

bool TransferSessionList::possibleToCreateNew()
{
    std::shared_lock lock (m_mutex);

    return Config::instance().transferSessionCountLimit() > m_map.size();
}

void TransferSessionList::remove(const std::string &id)
{   
    /*
     * An approach that ensures deletion after the mutex is released,
     * so as not to catch a deadlock during mutex calls that are
     * generated by session deletion.
     */

    std::shared_ptr<TransferSession> session = nullptr;
    {
        std::unique_lock lock (m_mutex);
        auto iter = m_map.find(id);
        if (iter == m_map.end())
        {
            return;
        }
        session = iter->second.session;
        m_map.erase(iter);
    }
}

TransferSessionList::TransferSessionList()
{
    m_ioContextThreadPtr = std::make_unique<std::thread>([&]() {
        asio::executor_work_guard<asio::io_context::executor_type> work = asio::make_work_guard(m_ioContext);
        m_ioContext.run();
    });
}
