#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INPUT="$SCRIPT_DIR/dist/index.html"
OUTPUT="$SCRIPT_DIR/../src/generated_index_html.h"

if [ ! -f "$INPUT" ]; then
    echo "Error: $INPUT not found. Run 'npm run build' in web/ first." >&2
    exit 1
fi

echo "Embedding $INPUT -> $OUTPUT"

python3 -c "
import sys

with open(sys.argv[1], 'rb') as f:
    data = f.read()

print('// Auto-generated by web/embed.sh — do not edit manually')
print('#pragma once')
print('#include <string>')
print()
print(f'static const unsigned char _index_html_data[{len(data)}] = {{')

for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    line = ', '.join(f'0x{b:02x}' for b in chunk)
    if i + 16 < len(data):
        line += ','
    print(f'  {line}')

print('};')
print()
print('static inline std::string getIndexHtml() {')
print(f'    return std::string(reinterpret_cast<const char*>(_index_html_data), {len(data)});')
print('}')
" "$INPUT" > "$OUTPUT"

echo "Done: $(wc -c < "$OUTPUT") bytes"
